name: Build & Deploy frontend to Namecheap (public_html)

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps (frontend)
        working-directory: frontend
        run: npm ci

      - name: Build (Vite)
        working-directory: frontend
        env:
          CI: 'true'
        run: npm run build

      - name: FTP Deploy to Namecheap /public_html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}       # server902.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }}   # deploy@bizdetails.xyz
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}           # 21
          protocol: ftp
          # local-dir must end with a trailing slash for FTP-Deploy-Action
          local-dir: frontend/dist/
          server-dir: .
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
